apiVersion: v1
kind: Secret
metadata:
  name: workshop-secret
type: Opaque
stringData:
  instance: astronomy-shop
  app: astronomy-shop-store
  env: astronomy-shop
  deployment: "deployment.environment=astronomy-shop"
  realm: eu0
  access_token: <access_token>
  api_token: <api_token>
  rum_token: <rum_token>
  url: <external url from gateway>
  flagd_auth: "false"